services:
  fw:
    image: debian:stable-slim
    container_name: fw
    privileged: true
    volumes:
      - ./setup_nic.sh:/usr/local/bin/setup_nic.sh:ro
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y iproute2 && sh /usr/local/bin/setup_nic.sh && tail -f /dev/null"]
    ports:
      - "8080:8080"
    restart: unless-stopped


  ether-book:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ether-book
    # fw と同じネットワーク名前空間を共有
    network_mode: "service:fw"
    environment:
      - LIVEBOOK_TOKEN_ENABLED=false
      - LIVEBOOK_HOME=/home/ex_tcp/livebook
      - LIVEBOOK_PORT=8080
      - EX_TCP_ROOT=/home/ex_tcp
    volumes:
      - ./ex_tcp:/home/ex_tcp
    # Livebook を動かすユーザ（必要に応じて調整）
    user: "${host_uid:-1000}:${host_gid:-1000}"
    working_dir: /home/ex_tcp/livebook
    depends_on:
      - fw
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
